name: streetaiability
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.9.0
  js: ^0.6.7
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.9.0
  image: ^4.1.3
  http: ^0.13.6
  geocoding: ^2.1.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  uuid: ^4.2.2
  universal_html: ^2.2.4
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  cupertino_icons: ^1.0.8
  flutter_google_street_view: ^3.1.4
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/icons/
    - assets/profiles/
    - assets/profiles/felix.jpg
    - assets/profiles/bela.jpg
    - assets/profiles/josefine.jpg
    - assets/profiles/jacqueline.jpg
    - assets/profiles/laila.jpg
